### ISSUE TITLE
Translate Cloud Functions Guide for Node.js, Python, Java, and PHP

### ISSUE THREAD

**Issue by hjiang** [leancloud/docs-en#12]

**Comment by myleslee** [comment]
「Con 表达式」这部分不需要重新翻译
https://leancloud.cn/docs/leanengine_cloudfunction_guide-node.html#hash-2143744582

原来就是从英文文档里翻译过来的：
http://www.quartz-scheduler.org/documentation/quartz-1.x/tutorials/crontrigger
