### ISSUE TITLE
去除所有中国节点相关内容

### ISSUE THREAD

**Issue by ghost** [leancloud/docs-en#30]
https://docs.leancloud.app/sms-guide.html#hash-315056186

现在美国区已经用美元计费了，短信发送费用可以用美元展示。

**Comment by leeyeh** [comment]
[价格列表](https://github.com/leancloud/uluru-platform/blob/master/uluru-commons/resources/sms_pricing.json)

**Comment by ghost** [comment]
我们对国外用户开放中国区域短信服务吗？如果是的话，是否也要用美元计费（现在[价格列表](https://github.com/leancloud/uluru-platform/blob/master/uluru-commons/resources/sms_pricing.json)里中国区域用的还是人民币）？

**Comment by leeyeh** [comment]
美国节点往中国号码发短信的价格是 0.0336 美元。

https://github.com/leancloud/uluru-platform/blob/5584206b6673cc61819380e54bdede0dc9fb35a3/uluru-commons/resources/sms_pricing.json#L5

**Comment by ghost** [comment]
想确认一下以后在 https://leancloud.app 注册的用户是否能够在中国节点创建应用。如果这些用户 _只能_ 访问美国节点的话那就没问题了（这样的话英文文档 Pricing 里面中国节点的价格也可以去掉）。

但是如果这部分用户可以访问中国节点，并且会用美元付费，那我们还需要明确一下「中国节点往中国号码发短信的价格是 ____ 美元」。

**Comment by leeyeh** [comment]
不用，美国节点可以看作是独立运营的一个服务，包括价格与文档。

**Comment by ghost** [comment]
那我们就把所有英文文档里对中国节点的相关说明给去掉吧，包括价格、API 地址等等。
